Mutiple include
bugy/script-server pull request #423
Opened 2021-03-30 13:33 UTC by brunomgalmeida

Allow import of multiple files
will only care about the json section "parameters"

2021-04-04 10:01 UTC, bugy requested changes
Hey, I think the idea of the PR is super nice and thanks for the initial changes!
Unfotunately, I think we should improve the implementation. I left a couple of comments in the code. Additionally, we would need to consider the following things:
- Each included path can depend on other parameters: e.g. `"include": "configs/${list1}.json"` That's why there was "_TemplateProperty" used. Unfortunately for the list this would be much more difficult to implement (we would need to listen on changes in any element of the list)
- Could you add a couple of tests for it?

2023-03-12 09:37 UTC, bugy approved these changes

2023-03-12 09:50 UTC, merged

2024-05-29 10:11 UTC, muzzol commented
sorry to resurface this old issue.

can this solution be used in conf.json?

for security purposes I need a separated file with access info but I don't see any include example on main conf file.

is this possible?

2024-05-30 07:54 UTC, bugy commented
Hey @muzzol unfortunately not :(